baseURL = "http://entrainpro.com/"
languageCode = "en-us"
title = "Entrain: Fire Dynamics Trainer"
theme = "hugograyscale"
[Params]
    # Provide some metadata for search and indexing services
    description = "Project page for Entrain: Fire Dynamics Trainer"
    author = "Kevin MacPhail"
